# Generated by Django 5.1.7 on 2025-03-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmain',
            name='title1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
