# Generated by Django 5.1.7 on 2025-03-24 08:57

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDMParentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'CDM Parent Sections',
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'FAQ Categories',
            },
        ),
        migrations.CreateModel(
            name='FeaturesTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Features Tabs',
            },
        ),
        migrations.CreateModel(
            name='FileFAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'File FAQ Categories',
            },
        ),
        migrations.CreateModel(
            name='FileNestedFAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'File Nested FAQ Sections',
            },
        ),
        migrations.CreateModel(
            name='GalleryMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Gallery Mains',
            },
        ),
        migrations.CreateModel(
            name='GreenPromoCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the section', max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('addrss_bar', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cta1_text', models.CharField(blank=True, help_text='Text for the first call-to-action button', max_length=100, null=True)),
                ('cta1_url', models.CharField(blank=True, help_text='URL for the first call-to-action button', null=True)),
                ('cta2_text', models.CharField(blank=True, help_text='Text for the second call-to-action button', max_length=100, null=True)),
                ('cta2_url', models.CharField(blank=True, help_text='URL for the second call-to-action button', null=True)),
            ],
            options={
                'verbose_name_plural': 'Green Promo CTAs',
            },
        ),
        migrations.CreateModel(
            name='IslamicFAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Islamic FAQ Sections',
            },
        ),
        migrations.CreateModel(
            name='IslamicRecurringDepositPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Islamic Recurring Deposit Pages',
            },
        ),
        migrations.CreateModel(
            name='multirowpromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Multi Row Promos',
            },
        ),
        migrations.CreateModel(
            name='multirowpromoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Multi Row Promo Items',
            },
        ),
        migrations.CreateModel(
            name='NestedFAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Nested FAQ Sections',
            },
        ),
        migrations.CreateModel(
            name='SupplyChainFinancePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Supply Chain Finance Pages',
            },
        ),
        migrations.CreateModel(
            name='TabData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Tab Data',
            },
        ),
        migrations.CreateModel(
            name='TilePromoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='tilepromo_icons/')),
                ('icon_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tile Promo Items',
            },
        ),
        migrations.CreateModel(
            name='TilePromoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tile Promo Sections',
            },
        ),
        migrations.CreateModel(
            name='WomenServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Women Services Pages',
            },
        ),
        migrations.CreateModel(
            name='AccountsPageIslamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('accounts_promo_all', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AccountsPageIslamic', to='core.accountsection')),
                ('footer_section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AccountsPageIslamic', to='core.footersection')),
                ('hero_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AccountsPageIslamic', to='core.herosection')),
                ('navbar', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('promo_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobanner')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_page_sub_nav', to='core.navigationmain')),
            ],
            options={
                'verbose_name_plural': 'Accounts Pages Islamic',
            },
        ),
        migrations.CreateModel(
            name='CardPromoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cards', models.ManyToManyField(related_name='CardPromoSection', to='core.card')),
            ],
            options={
                'verbose_name_plural': 'Card Promo Sections',
            },
        ),
        migrations.CreateModel(
            name='CardsPromoPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CardsPromoPages', to='islamic_core.cardpromosection')),
                ('footer_section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CardsPromoPages', to='core.footersection')),
                ('hero_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CardsPromoPages', to='core.herosection')),
                ('navbar', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('promo_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobanner')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_promo_sub_nav', to='core.navigationmain')),
            ],
            options={
                'verbose_name_plural': 'Cards Promo Pages',
            },
        ),
        migrations.CreateModel(
            name='CDMPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('footer_section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CDMPage', to='core.footersection')),
                ('hero_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CDMPage', to='core.herosection')),
                ('navbar', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('promo_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobanner')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdm_sub_nav', to='core.navigationmain')),
                ('cdm_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdm_pages', to='islamic_core.cdmparentsection')),
            ],
            options={
                'verbose_name_plural': 'CDM Pages',
            },
        ),
        migrations.CreateModel(
            name='CDMDataSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('parent_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdm_entries', to='islamic_core.cdmparentsection')),
            ],
            options={
                'verbose_name_plural': 'CDM Data Sections',
            },
        ),
        migrations.CreateModel(
            name='FAQQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_question_answers', to='islamic_core.faqcategory')),
            ],
            options={
                'verbose_name_plural': 'FAQ Question Answers',
            },
        ),
        migrations.CreateModel(
            name='FileFAQQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('small_desc', models.CharField(max_length=255)),
                ('file_cta_text', models.CharField(max_length=255)),
                ('file_cta_url', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_faq_question_answers', to='islamic_core.filefaqcategory')),
            ],
            options={
                'verbose_name_plural': 'File FAQ Question Answers',
            },
        ),
        migrations.AddField(
            model_name='filefaqcategory',
            name='nested_faq_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_faq_categories', to='islamic_core.filenestedfaqsection'),
        ),
        migrations.CreateModel(
            name='GalleryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='islamic_gallery/')),
                ('video', models.FileField(blank=True, help_text='Upload the video file.', null=True, upload_to='aboutus_videos/')),
                ('main_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_entries', to='islamic_core.gallerymain')),
            ],
            options={
                'verbose_name_plural': 'Gallery Data',
            },
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('footer_section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='GalleryPage', to='core.footersection')),
                ('gallery_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_page_entry', to='islamic_core.gallerymain')),
                ('hero_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GalleryPage', to='core.herosection')),
                ('navbar', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_sub_nav', to='core.navigationmain')),
            ],
            options={
                'verbose_name_plural': 'Gallery Pages',
            },
        ),
        migrations.CreateModel(
            name='AlfaBNPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('footer_section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AlfaBNPL', to='core.footersection')),
                ('hero_sections', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AlfaBNPL', to='core.herosection')),
                ('navbar', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bnpl_sub_nav', to='core.navigationmain')),
                ('green_cta_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AlfaBNPL', to='islamic_core.greenpromocta')),
            ],
            options={
                'verbose_name_plural': 'Alfa BNPLs',
            },
        ),
        migrations.CreateModel(
            name='AboutUsIslamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('footer_section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='AboutUsIslamic', to='core.footersection')),
                ('hero_sections', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AboutUsIslamic', to='core.herosection')),
                ('image_text_promo', models.ManyToManyField(related_name='AboutUsIslamic', to='core.accountfeature')),
                ('navbar', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('promo_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobanner')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abt_us_sub_nav', to='core.navigationmain')),
                ('text_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AboutUsIslamic', to='core.articlesection')),
                ('file_faq_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AboutUsIslamic', to='islamic_core.filenestedfaqsection')),
                ('green_cta_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AboutUsIslamic', to='islamic_core.greenpromocta')),
            ],
            options={
                'verbose_name_plural': 'About Us Islamic',
            },
        ),
        migrations.CreateModel(
            name='IslamicAccountFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('card_info_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_1', to='core.tablepromo')),
                ('card_info_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_2', to='core.tablepromo')),
                ('eligibility_docs', models.ManyToManyField(blank=True, to='core.eligibilitydoctile')),
                ('faq_islamic', models.ManyToManyField(related_name='faq_islamic', to='core.faqitem')),
                ('footer_section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='IslamicAccountFeature', to='core.footersection')),
                ('hero_sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IslamicAccountFeature', to='core.herosection')),
                ('navbar', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('promo_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobanner')),
                ('promo_banner_full', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobannerfull')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_feature_sub_nav', to='core.navigationmain')),
            ],
            options={
                'verbose_name_plural': 'Islamic Account Features',
            },
        ),
        migrations.CreateModel(
            name='IslamicFAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('top_description', ckeditor.fields.RichTextField()),
                ('mid_description', ckeditor.fields.RichTextField()),
                ('bottom_description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='faq_islamic_images/')),
                ('faq_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islamic_faq_items', to='islamic_core.islamicfaqsection')),
            ],
            options={
                'verbose_name_plural': 'Islamic FAQ Items',
            },
        ),
        migrations.CreateModel(
            name='IslamicHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('account_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islamic_homepages', to='core.accountpromo')),
                ('banking_promo', models.ManyToManyField(blank=True, related_name='islamic_homepages', to='core.bankingpromo')),
                ('financial_solution_promo', models.ManyToManyField(blank=True, related_name='islamic_homepages', to='core.financialsolutionpromo')),
                ('footer_section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='islamic_homepages', to='core.footersection')),
                ('hero_sections', models.ManyToManyField(related_name='islamic_homepages', to='core.herosection')),
                ('hero_slider_sections', models.ManyToManyField(blank=True, related_name='isl_homepages', to='core.herosectionslider')),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islamic_homepages', to='core.navigationmain')),
                ('news_updates', models.ManyToManyField(related_name='islamic_homepages', to='core.newsupdate')),
                ('offers_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islamic_homepages', to='core.offerspromo')),
                ('promo_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islamic_homepages', to='core.promobanner')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isl_sub_nav', to='core.navigationmain')),
            ],
            options={
                'verbose_name_plural': 'Islamic Homepage',
            },
        ),
        migrations.CreateModel(
            name='IslamicMisc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('footer_section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='misc_footer', to='core.footersection')),
            ],
            options={
                'verbose_name_plural': 'Islamic Misc',
            },
        ),
    ]
