# Generated by Django 5.1.7 on 2025-03-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('dbg', '0002_initial'),
        ('islamic_core', '0001_initial'),
        ('premier_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='islamicmisc',
            name='green_cta_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='green_cta_promo', to='premier_core.goldenpromoctaentry'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='hero_sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islamic_misc', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='isl_col_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isl_col_text', to='dbg.textcoldbg'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='isl_col_text_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isl_col_text_2', to='dbg.textcoldbg'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='isl_faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isl_faq', to='core.faqsection'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='isl_full_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isl_full_text', to='dbg.textfulldbg'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='isl_full_text_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isl_full_text_2', to='dbg.textfulldbg'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='isl_full_text_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isl_full_text_3', to='dbg.textfulldbg'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='isl_full_text_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isl_full_text_4', to='dbg.textfulldbg'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='isl_promo_orbit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isl_orbit_rewards', to='premier_core.orbitpromo'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='isl_table_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isl_table_1', to='core.tablepromo'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='isl_table_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isl_table_2', to='core.tablepromo'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='isl_zigzag',
            field=models.ManyToManyField(blank=True, related_name='isl_zigzag', to='core.accountfeature'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='navbar',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain'),
        ),
        migrations.AddField(
            model_name='islamicmisc',
            name='subnav',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misc_sub_nav', to='core.navigationmain'),
        ),
        migrations.AddField(
            model_name='islamicrecurringdepositpage',
            name='eligibility_docs',
            field=models.ManyToManyField(blank=True, to='core.eligibilitydoctile'),
        ),
        migrations.AddField(
            model_name='islamicrecurringdepositpage',
            name='faq_islamic_recurring',
            field=models.ManyToManyField(related_name='IslamicRecurringDepositPage', to='core.faqitem'),
        ),
        migrations.AddField(
            model_name='islamicrecurringdepositpage',
            name='footer_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='IslamicRecurringDepositPage', to='core.footersection'),
        ),
        migrations.AddField(
            model_name='islamicrecurringdepositpage',
            name='hero_sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IslamicRecurringDepositPage', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='islamicrecurringdepositpage',
            name='navbar',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain'),
        ),
        migrations.AddField(
            model_name='islamicrecurringdepositpage',
            name='promo_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobanner'),
        ),
        migrations.AddField(
            model_name='islamicrecurringdepositpage',
            name='subnav',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rec_sub_nav', to='core.navigationmain'),
        ),
        migrations.AddField(
            model_name='multirowpromoitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multirowpromo', to='islamic_core.multirowpromo'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='nested_faq_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_categories', to='islamic_core.nestedfaqsection'),
        ),
        migrations.AddField(
            model_name='alfabnpl',
            name='faq_islamic_nested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AlfaBNPL', to='islamic_core.nestedfaqsection'),
        ),
        migrations.AddField(
            model_name='supplychainfinancepage',
            name='faq_islamic_recurring',
            field=models.ManyToManyField(related_name='SupplyChainFinancePage', to='core.faqitem'),
        ),
        migrations.AddField(
            model_name='supplychainfinancepage',
            name='footer_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SupplyChainFinancePage', to='core.footersection'),
        ),
        migrations.AddField(
            model_name='supplychainfinancepage',
            name='hero_sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SupplyChainFinancePage', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='supplychainfinancepage',
            name='navbar',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain'),
        ),
        migrations.AddField(
            model_name='supplychainfinancepage',
            name='row_promo_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='row_promo_1', to='islamic_core.multirowpromo'),
        ),
        migrations.AddField(
            model_name='supplychainfinancepage',
            name='row_promo_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='row_promo_2', to='islamic_core.multirowpromo'),
        ),
        migrations.AddField(
            model_name='supplychainfinancepage',
            name='subnav',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sup_sub_nav', to='core.navigationmain'),
        ),
        migrations.AddField(
            model_name='tabdata',
            name='features_tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_data', to='islamic_core.featurestab'),
        ),
        migrations.AddField(
            model_name='supplychainfinancepage',
            name='tab_section',
            field=models.ManyToManyField(related_name='SupplyChainFinancePage', to='islamic_core.tabdata'),
        ),
        migrations.AddField(
            model_name='islamicrecurringdepositpage',
            name='tab_section',
            field=models.ManyToManyField(related_name='IslamicRecurringDepositPage', to='islamic_core.tabdata'),
        ),
        migrations.AddField(
            model_name='islamicaccountfeature',
            name='tab_section',
            field=models.ManyToManyField(related_name='IslamicAccountFeature', to='islamic_core.tabdata'),
        ),
        migrations.AddField(
            model_name='alfabnpl',
            name='tab_section',
            field=models.ManyToManyField(related_name='AlfaBNPL', to='islamic_core.tabdata'),
        ),
        migrations.AddField(
            model_name='tilepromoitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile_promo_items', to='islamic_core.tilepromosection'),
        ),
        migrations.AddField(
            model_name='alfabnpl',
            name='tile_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='islamic_core.tilepromosection'),
        ),
        migrations.AddField(
            model_name='womenservicespage',
            name='faq_islamic',
            field=models.ManyToManyField(related_name='WomenServicesPage', to='islamic_core.islamicfaqitem'),
        ),
        migrations.AddField(
            model_name='womenservicespage',
            name='footer_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='WomenServicesPage', to='core.footersection'),
        ),
        migrations.AddField(
            model_name='womenservicespage',
            name='hero_sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WomenServicesPage', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='womenservicespage',
            name='navbar',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain'),
        ),
        migrations.AddField(
            model_name='womenservicespage',
            name='promo_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobanner'),
        ),
        migrations.AddField(
            model_name='womenservicespage',
            name='subnav',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wom_sub_nav', to='core.navigationmain'),
        ),
    ]
