# Generated by Django 5.1.7 on 2025-03-24 08:57

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Box Promos',
            },
        ),
        migrations.CreateModel(
            name='DBGAllText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'DBG All Texts',
            },
        ),
        migrations.CreateModel(
            name='DBGCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=50, null=True)),
                ('cta_link', models.CharField(blank=True, max_length=200, null=True)),
                ('cta_text_2', models.CharField(blank=True, max_length=50, null=True)),
                ('cta_link_2', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dbg_account_card_images/')),
            ],
            options={
                'verbose_name_plural': 'DBG Cards',
            },
        ),
        migrations.CreateModel(
            name='DBGVideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('video', models.FileField(help_text='Upload the video file.', upload_to='videos/')),
            ],
            options={
                'verbose_name_plural': 'DBG Video Sections',
            },
        ),
        migrations.CreateModel(
            name='FeaturesBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Features Boxes',
            },
        ),
        migrations.CreateModel(
            name='FeaturesBoxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Features Box Entries',
            },
        ),
        migrations.CreateModel(
            name='KeyFactsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='key_facts_images/')),
                ('cta_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Key Facts Sections',
            },
        ),
        migrations.CreateModel(
            name='ProductTextDBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Product Text DBGs',
            },
        ),
        migrations.CreateModel(
            name='SupportServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Support Services',
            },
        ),
        migrations.CreateModel(
            name='SupportServicesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='support_service_logos/')),
            ],
            options={
                'verbose_name_plural': 'Support Services Entries',
            },
        ),
        migrations.CreateModel(
            name='TextColDBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Text Col DBGs',
            },
        ),
        migrations.CreateModel(
            name='TextColDBGEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading_column1', models.CharField(blank=True, max_length=255, null=True)),
                ('main_description_column1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('main_heading_column2', models.CharField(blank=True, max_length=255, null=True)),
                ('main_description_column2', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Text Col DBG Entries',
            },
        ),
        migrations.CreateModel(
            name='TextFullDBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Text Full DBGs',
            },
        ),
        migrations.CreateModel(
            name='TextFullDBGEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=255)),
                ('main_description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Text Full DBG Entries',
            },
        ),
        migrations.CreateModel(
            name='BoxPromoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dbg_box_promo_logos/')),
                ('box_promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_entries', to='dbg.boxpromo')),
            ],
            options={
                'verbose_name_plural': 'Box Promo Entries',
            },
        ),
        migrations.CreateModel(
            name='DBGAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Convetional', 'Convetional'), ('Islamic', 'Islamic'), ('RDA', 'RDA')], max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dbg_account_tabs_images/')),
                ('cards', models.ManyToManyField(related_name='dbg_account_types', to='core.card')),
            ],
            options={
                'verbose_name_plural': 'DBG Accounts',
            },
        ),
        migrations.CreateModel(
            name='DBGAccountSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title for the section', max_length=255)),
                ('secondary_title', models.CharField(max_length=255)),
                ('account_types', models.ManyToManyField(related_name='dbg_accounts', to='dbg.dbgaccount')),
            ],
            options={
                'verbose_name_plural': 'DBG Account Sections',
            },
        ),
        migrations.CreateModel(
            name='DBGPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dbg_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_accounts', to='core.accountsection')),
                ('dbg_accounts_promo_all', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DBG_Account', to='dbg.dbgaccountsection')),
                ('dbg_box_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_box', to='dbg.boxpromo')),
                ('dbg_box_promo_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_box_2', to='dbg.boxpromo')),
                ('dbg_box_promo_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_box_3', to='dbg.boxpromo')),
            ],
            options={
                'verbose_name_plural': 'DBG Pages',
            },
        ),
    ]
