# Generated by Django 5.1.7 on 2025-03-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('dbg', '0001_initial'),
        ('islamic_core', '0001_initial'),
        ('premier_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_cards', to='islamic_core.cardpromosection'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_faq', to='core.faqsection'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_faq_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_faq_2', to='core.faqsection'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_faq_nested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_faq_nested', to='premier_core.nestedfaqpremier'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_file_faq_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_file_section', to='islamic_core.filenestedfaqsection'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_promo_orbit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_orbit_rewards', to='premier_core.orbitpromo'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_reports_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_reports', to='core.reportstabsection'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_table_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_table_1', to='core.tablepromo'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_table_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_table_2', to='core.tablepromo'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_table_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_table_3', to='core.tablepromo'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_table_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_table_4', to='core.tablepromo'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_table_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_table_5', to='core.tablepromo'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_text_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_text', to='dbg.dbgalltext'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_zigzag',
            field=models.ManyToManyField(blank=True, related_name='dbg_zigzag', to='core.accountfeature'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='footer_section',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='dbg_footer', to='core.footersection'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='hero_sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_hero', to='core.herosection'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='navbar',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='promo_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobanner'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='promo_banner_full',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobannerfull'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='red_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_red_promo', to='premier_core.goldenpromoctaentry'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='red_promo_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_red_promo_2', to='premier_core.goldenpromoctaentry'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='red_promo_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_red_promo_3', to='premier_core.goldenpromoctaentry'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='subnav',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_subnav', to='core.navigationmain'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_video', to='dbg.dbgvideosection'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_features', to='dbg.featuresbox'),
        ),
        migrations.AddField(
            model_name='featuresboxentry',
            name='features_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_box_entries', to='dbg.featuresbox'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='key_facts',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_key_facts', to='dbg.keyfactssection'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_product_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_product_text', to='dbg.producttextdbg'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_services', to='dbg.supportservices'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_tips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_tips', to='dbg.supportservices'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='services_promo_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_service_1', to='dbg.supportservices'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='services_promo_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_service_2', to='dbg.supportservices'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='services_promo_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_service_3', to='dbg.supportservices'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='services_promo_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_service_4', to='dbg.supportservices'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='services_promo_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_service_5', to='dbg.supportservices'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='services_promo_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_service_6', to='dbg.supportservices'),
        ),
        migrations.AddField(
            model_name='supportservicesentry',
            name='support_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_entries', to='dbg.supportservices'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_col_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_col_text', to='dbg.textcoldbg'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_col_text_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_col_text_2', to='dbg.textcoldbg'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_col_text_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_col_text_3', to='dbg.textcoldbg'),
        ),
        migrations.AddField(
            model_name='textcoldbgentry',
            name='text_full_dbg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbg_col_entries', to='dbg.textcoldbg'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_full_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_full_text', to='dbg.textfulldbg'),
        ),
        migrations.AddField(
            model_name='dbgpages',
            name='dbg_full_text_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dbg_full_text_2', to='dbg.textfulldbg'),
        ),
        migrations.AddField(
            model_name='textfulldbgentry',
            name='text_full_dbg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbg_full_entries', to='dbg.textfulldbg'),
        ),
    ]
