# Generated by Django 5.1.7 on 2025-03-24 08:57

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('islamic_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading_full_width', models.CharField(blank=True, max_length=255, null=True)),
                ('full_width_first_column_data', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('full_width_second_column_data', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('heading_half_width_1', models.CharField(blank=True, max_length=255, null=True)),
                ('half_width_1_data', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('heading_half_width_2', models.CharField(blank=True, max_length=255, null=True)),
                ('half_width_2_data', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Column Sections',
            },
        ),
        migrations.CreateModel(
            name='ContactUsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contact Us Data',
            },
        ),
        migrations.CreateModel(
            name='FinanceProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Finance Programs',
            },
        ),
        migrations.CreateModel(
            name='GoldenPromoCTAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Golden Promo CTA Entries',
            },
        ),
        migrations.CreateModel(
            name='LogosPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Logos Promos',
            },
        ),
        migrations.CreateModel(
            name='MultiColumnFAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Multi Column FAQ Sections',
            },
        ),
        migrations.CreateModel(
            name='NestedFAQPremier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Nested FAQ Premiers',
            },
        ),
        migrations.CreateModel(
            name='OrbitPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Orbit Promos',
            },
        ),
        migrations.CreateModel(
            name='StepsPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('steps_image', models.ImageField(blank=True, upload_to='steps_images/')),
            ],
            options={
                'verbose_name_plural': 'Steps Promos',
            },
        ),
        migrations.CreateModel(
            name='ContactUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('footer_section', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='contact_us', to='core.footersection')),
                ('hero_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_us', to='core.herosection')),
                ('location_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_us', to='premier_core.contactusdata')),
                ('navbar', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='con_sub_nav', to='core.navigationmain')),
            ],
            options={
                'verbose_name_plural': 'Contact Us Pages',
            },
        ),
        migrations.CreateModel(
            name='FinanceProgramDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='premier_core.financeprogram')),
            ],
            options={
                'verbose_name_plural': 'Finance Program Details',
            },
        ),
        migrations.CreateModel(
            name='GoldenPromoCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('cta1_text', models.CharField(blank=True, max_length=100, null=True)),
                ('cta1_url', models.CharField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gold_promo_cta/')),
                ('gold_promo_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items_golden', to='premier_core.goldenpromoctaentry')),
            ],
            options={
                'verbose_name_plural': 'Golden Promo CTAs',
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('account_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_home', to='core.accountpromo')),
                ('banking_promo', models.ManyToManyField(blank=True, related_name='prem_home', to='core.bankingpromo')),
                ('financial_solution_promo', models.ManyToManyField(blank=True, related_name='prem_home', to='core.financialsolutionpromo')),
                ('footer_section', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='prem_home', to='core.footersection')),
                ('hero_sections', models.ManyToManyField(related_name='prem_home', to='core.herosection')),
                ('hero_slider_sections', models.ManyToManyField(blank=True, related_name='prem_homepages', to='core.herosectionslider')),
                ('navbar', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_home', to='core.navigationmain')),
                ('offers_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_home', to='core.offerspromo')),
                ('promo_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_home', to='core.promobanner')),
                ('reports_promo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_financial_reports', to='core.reportstabsection')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_sub_nav', to='core.navigationmain')),
            ],
            options={
                'verbose_name_plural': 'Homepages',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, max_length=100)),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('poc_name', models.CharField(blank=True, max_length=100)),
                ('poc_designation', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('phone_number_2', models.CharField(blank=True, max_length=20)),
                ('main_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='premier_core.contactusdata')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='LogosPromoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perks_logo', models.ImageField(blank=True, upload_to='logos_perks/')),
                ('perks_name', models.CharField(max_length=255)),
                ('logo_promo_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_promo', to='premier_core.logospromo')),
            ],
            options={
                'verbose_name_plural': 'Logos Promo Entries',
            },
        ),
        migrations.CreateModel(
            name='MultiColumnFAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('first_col_answer', ckeditor.fields.RichTextField()),
                ('second_col_answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('faq_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='premier_core.multicolumnfaqsection')),
            ],
            options={
                'verbose_name_plural': 'Multi Column FAQ Items',
            },
        ),
        migrations.CreateModel(
            name='MiscellenousPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_top', models.BooleanField(default=True)),
                ('show_calculator', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('account_features', models.ManyToManyField(blank=True, related_name='MiscellenousPages', to='core.accountfeature')),
                ('all_text_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPages', to='core.articlesection')),
                ('all_text_data_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPagesTextBottom', to='core.articlesection')),
                ('branch_logo_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_logo', to='premier_core.logospromo')),
                ('bullet_features', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premier_core.columnsection')),
                ('cards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPages', to='islamic_core.cardpromosection')),
                ('file_faq_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPages', to='islamic_core.filenestedfaqsection')),
                ('footer_section', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='MiscellenousPages', to='core.footersection')),
                ('golden_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPages', to='premier_core.goldenpromoctaentry')),
                ('hero_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPages', to='core.herosection')),
                ('location_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPages', to='premier_core.contactusdata')),
                ('logos_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premier_core.logospromo')),
                ('navbar', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('promo_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPages', to='core.promobanner')),
                ('promo_banner_full', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobannerfull')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miscel_sub', to='core.navigationmain')),
                ('table_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPages', to='core.tablepromo')),
                ('table_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPagesTable2', to='core.tablepromo')),
                ('table_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPagesTable3', to='core.tablepromo')),
                ('multi_column_faq_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MiscellenousPages', to='premier_core.multicolumnfaqsection')),
            ],
            options={
                'verbose_name_plural': 'Miscellaneous Pages',
            },
        ),
        migrations.CreateModel(
            name='HomeFinancePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_finance_page', to='islamic_core.cardpromosection')),
                ('footer_section', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='home_finance_page', to='core.footersection')),
                ('hero_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_finance_page', to='core.herosection')),
                ('location_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_finance_page', to='premier_core.contactusdata')),
                ('navbar', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('promo_banner_full', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobannerfull')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hf_sub_nav', to='core.navigationmain')),
                ('multi_column_faq_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_finance_page', to='premier_core.multicolumnfaqsection')),
            ],
            options={
                'verbose_name_plural': 'Home Finance Pages',
            },
        ),
        migrations.CreateModel(
            name='OrbitPromoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orbit_logo', models.ImageField(blank=True, upload_to='steps_images/')),
                ('orbit_heading', models.CharField(max_length=255)),
                ('orbit_description', ckeditor.fields.RichTextField()),
                ('orbit_cta_text', models.CharField(max_length=255)),
                ('orbit_cta_link', models.CharField(max_length=255)),
                ('orbit_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orbit_promo', to='premier_core.orbitpromo')),
            ],
            options={
                'verbose_name_plural': 'Orbit Promo Entries',
            },
        ),
        migrations.CreateModel(
            name='OrbitRewardPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('account_features', models.ManyToManyField(blank=True, related_name='OrbitRewardPages', to='core.accountfeature')),
                ('footer_section', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='OrbitRewardPages', to='core.footersection')),
                ('hero_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrbitRewardPages', to='core.herosection')),
                ('navbar', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('orbit_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrbitRewardPages', to='premier_core.orbitpromo')),
                ('prem_faq_nested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrbitRewardPages', to='premier_core.nestedfaqpremier')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orbit_sub_nav', to='core.navigationmain')),
            ],
            options={
                'verbose_name_plural': 'Orbit Reward Pages',
            },
        ),
        migrations.CreateModel(
            name='PremierCardsPromoPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cards', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_card_promo', to='islamic_core.cardpromosection')),
                ('footer_section', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='prem_card_promo', to='core.footersection')),
                ('hero_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_card_promo', to='core.herosection')),
                ('navbar', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('promo_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobanner')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_prem_sub_nav', to='core.navigationmain')),
            ],
            options={
                'verbose_name_plural': 'Premier Cards Promo Pages',
            },
        ),
        migrations.CreateModel(
            name='PremierFAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('nested_faq_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_premier', to='premier_core.nestedfaqpremier')),
            ],
            options={
                'verbose_name_plural': 'Premier FAQ Categories',
            },
        ),
        migrations.CreateModel(
            name='PremierFAQQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_col_1', ckeditor.fields.RichTextField()),
                ('answer_col_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_premier_question_answers', to='premier_core.premierfaqcategory')),
            ],
            options={
                'verbose_name_plural': 'Premier FAQ Question Answers',
            },
        ),
        migrations.CreateModel(
            name='PremierIndividualAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('account_features', models.ManyToManyField(blank=True, related_name='prem_ind_details', to='core.accountfeature')),
                ('bullet_features', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premier_core.columnsection')),
                ('financial_program_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_ind_finance', to='premier_core.financeprogram')),
                ('footer_section', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='prem_ind_details', to='core.footersection')),
                ('golden_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_golden_promo', to='premier_core.goldenpromoctaentry')),
                ('hero_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_ind_details', to='core.herosection')),
                ('multi_column_faq_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_ind_faq', to='premier_core.multicolumnfaqsection')),
                ('navbar', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('prem_faq_nested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_ind_faq', to='premier_core.nestedfaqpremier')),
                ('promo_banner_full', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobannerfull')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_ind_sub_nav', to='core.navigationmain')),
                ('table_1_prem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_1_prem', to='core.tablepromo')),
                ('table_2_prem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_2_prem', to='core.tablepromo')),
                ('text_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prem_ind_text', to='core.articlesection')),
            ],
            options={
                'verbose_name_plural': 'Premier Individual Accounts',
            },
        ),
        migrations.CreateModel(
            name='FinancingOptionPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('account_features', models.ManyToManyField(blank=True, related_name='FinancingOptionPages', to='core.accountfeature')),
                ('cards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FinancingOptionPages', to='islamic_core.cardpromosection')),
                ('footer_section', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='FinancingOptionPages', to='core.footersection')),
                ('hero_sections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FinancingOptionPages', to='core.herosection')),
                ('navbar', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.navigationmain')),
                ('promo_banner_full', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promobannerfull')),
                ('subnav', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_sub_nav', to='core.navigationmain')),
                ('table_1_prem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FinancingOptionPages', to='core.tablepromo')),
                ('steps_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FinancingOptionPages', to='premier_core.stepspromo')),
            ],
            options={
                'verbose_name_plural': 'Financing Option Pages',
            },
        ),
        migrations.CreateModel(
            name='StepsPromoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.CharField(max_length=255)),
                ('step_description', ckeditor.fields.RichTextField()),
                ('step_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_promo', to='premier_core.stepspromo')),
            ],
            options={
                'verbose_name_plural': 'Steps Promo Entries',
            },
        ),
    ]
